### ISSUE TITLE
В вашем SELECT'е rs.getInt(1) когда-то может вернуть не 1?

### ISSUE THREAD

**Issue by coursar** [AmirSalakhov94/servlets#6]
https://github.com/AmirSalakhov94/servlets/blob/f3e072d44b846331ac375d4fac4031aaf3b20aca/src/main/java/tech/itpark/proggerhub/repository/AuthRepository.java#L205

**Comment by AmirSalakhov94** [comment]
SELECT 1 FROM users_password_restore WHERE login = ? AND key = ? AND is_valid IS TRUE;
это проверка на то, что у пользователя есть такой ключ и он валидный, тогда результат запроса будет - единица, в других случаях резульат будет отличен от единицы.

**Comment by coursar** [comment]
Разве в противном случае у вас не будет пустой результат, а значит `rs.next()` вернёт `false`?

**Comment by AmirSalakhov94** [comment]
понятно)
